### ISSUE TITLE
On reboot, ingress-nginx-controller pod stuck in CrashLoopBackOff state

### ISSUE THREAD

**Issue by rchen-virtru** [opentdf/opentdf#196]
We are using OpenTDF in in offline deployment mode (i.e. https://github.com/opentdf/opentdf/tree/main/examples/offline ).
If the box which hosts the cluster is reboot, everything comes back up, however the ingress-nginx-controller pod is stuck in CrashLoopBackOff loop.

For example:
```
ubuntu@host:~$ kubectl get pods
NAME                                        READY   STATUS             RESTARTS           AGE
abacus-fc9d8b5fb-49qzn                      1/1     Running            1 (5d15h ago)      27d
access-pep-84846f4ccf-2lg49                 1/1     Running            1 (5d15h ago)      27d
attributes-5795797754-47r9m                 1/1     Running            2 (5d15h ago)      27d
entitlement-pdp-554565d588-kk5zr            1/1     Running            2 (5d15h ago)      27d
entitlement-store-6b5f7f8dfc-2zfwv          1/1     Running            2 (5d15h ago)      27d
entitlements-bbc8bcd59-456s9                1/1     Running            2 (5d15h ago)      27d
entity-resolution-5b579bb8cb-z8489          1/1     Running            3 (5d15h ago)      27d
ingress-nginx-controller-6d7767579d-g6ktc   0/1     CrashLoopBackOff   2206 (2m38s ago)   27d
kas-75b7b47d86-ds9ts                        1/1     Running            1 (5d15h ago)      27d
keycloak-0                                  1/1     Running            1 (5d15h ago)      27d
keycloak-bootstrap-sxc95                    0/1     Completed          0                  27d
postgresql-postgresql-0                     1/1     Running            1 (5d15h ago)      27d
registry-docker-registry-74bfb84db6-hnhsj   1/1     Running            1 (5d15h ago)      27d
```

Last tested with **OpenTDF v1.1.1** and seeing this behavior consistently (i.e. on every reboot).
Logs from the pod are attached.
[ingress-nginx-controller.log](https://github.com/opentdf/opentdf/files/10438547/ingress-nginx-controller.log)

Even though the pod is in CrashLoopBackOff state, the entire system is working... Abacus, Keycloak, and all of the other ingresses function normally.

**How to reproduce:**
1. Deploy a new instance of the OpenTDF stack.  (NOTE: we have been doing so using offline mode -- have not tried Tilt to see if it behaves the same or not).
2. Reboot the host box.
3. On reboot, observe state of ingress-nginx-controller.  We never see it get back to READY.

**Comment by rchen-virtru** [comment]
See same problem with OpenTDF v1.2.1.
Also tried updating nginx controller to the latest v1.7.0, and have same issue.

**Comment by dmihalcik-virtru** [comment]
It may be a permissions error with the ingress controller, at least the logs seem to indicate this.

For disconnected k8s mode, ingress is saved [here](https://github.com/opentdf/opentdf/blob/main/examples/offline/build-offline-bundle#L185) and [configured here](https://github.com/opentdf/opentdf/blob/main/quickstart/start.sh#L295).

Does this happen on first install, or on an upgrade?

**Comment by rchen-virtru** [comment]
> It may be a permissions error with the ingress controller, at least the logs seem to indicate this.
> 
> For disconnected k8s mode, ingress is saved [here](https://github.com/opentdf/opentdf/blob/main/examples/offline/build-offline-bundle#L185) and [configured here](https://github.com/opentdf/opentdf/blob/main/quickstart/start.sh#L295).
> 
> Does this happen on first install, or on an upgrade?


This happens after reboot.
On install, everything is running normally.   And then after doing a reboot, the pod gets stuck in the CrashLoopBackOff.

**Comment by robryb** [comment]
I am new to OpenTDF, trying it out for the first time. I am running on Windows 10 (corporate laptop, I have limited admin privs). I had some trouble getting WSL2 to play along, but all the parts are working now except for ingress-nginx. 

One difference I see from the initial report:

> NOTE: we have been doing so using offline mode -- have not tried Tilt to see if it behaves the same or not.

I installed using Tilt (and restarted using Tilt) but had slightly different results. Tilt dashboard always reported the ingress-nginx status as "Server: unhealthy", including during initial installation. There were/are no error messages in the startup log. 

Another minor difference: "kubectl get pods" also reported ImagePullBackoff but I get no restarts. I thought that was odd.

| NAME                                                          | READY |  STATUS   |                 RESTARTS  |    AGE |
| ---------------------------------------------- | ------- | ------ | ----- | ----- |
| ingress-nginx-controller-644d48dff-h5kv2 |   0/1   |      ImagePullBackOff |  0  |                  15h |

Please let me know if I you'd like any other information.

**Comment by cassandrabailey293** [comment]
Hi, thank you for your comment.

It seems based on this that there is a failure to pull nginx/controller from google cloud platform (`k8s.gcr.io`):

```
[event: pod ingress-nginx-controller-644d48dff-9h6qs] Failed to pull image "k8s.gcr.io/ingress-nginx/controller:v1.1.1@sha256:0bc88eb15f9e7f84e8e56c14fa5735aaa488b840983f87bd79b1054190e660de": rpc error: code = Unknown desc = failed to pull and unpack image "k8s.gcr.io/ingress-nginx/controller@sha256:0bc88eb15f9e7f84e8e56c14fa5735aaa488b840983f87bd79b1054190e660de": failed to resolve reference "k8s.gcr.io/ingress-nginx/controller@sha256:0bc88eb15f9e7f84e8e56c14fa5735aaa488b840983f87bd79b1054190e660de": failed to do request: Head "[https://k8s.gcr.io/v2/ingress-nginx/controller/manifests/sha256:0bc88eb15f9e7f84e8e56c14fa5735aaa488b840983f87bd79b1054190e660de":](https://k8s.gcr.io/v2/ingress-nginx/controller/manifests/sha256:0bc88eb15f9e7f84e8e56c14fa5735aaa488b840983f87bd79b1054190e660de%22:)
```

We are investigating and will try to suggest some remediation steps - do you have any additional details you can share?

Thank you!

**Comment by robryb** [comment]
Hi cassandrabailey293,

Unfortunately, I can reproduce the error every time. I mentioned that it fails on Windows 10 using WSL2. I also installed OpenTDF on my personal laptop, which runs Windows 11 (again using WSL2). It runs great on my personal laptop. However, I have to get it working on my corporate laptop in order to do my job.

It looks like it's failing on a self-signed cert (the x509 error message), but your team would know more about the cert used than I would. 

I tried using helm's --insecure-skip-tls-verify option and I could see it in the resulting logs, but that didn't make a difference.

Regarding my own skillset to debug this: I am okay with Docker, weak with k8s, I have no experience with helm, and I never heard of tilt before reading the Quickstart for OpenTDF. I will keep working on this, but I am not the best person to fix this bug.

**Comment by robryb** [comment]
I let OpenTDF run overnight on my corporate laptop. Tilt was green when I logged in this morning. This is great. I am going to leave what I think are the important log messages from the period when things started working again.

> [... many lines of the same thing as next ...]
>  [event: pod ingress-nginx-controller-644d48dff-v8gmp] Pulling image "k8s.gcr.io/ingress-nginx/controller:v1.1.1@sha256:0bc88eb15f9e7f84e8e56c14fa5735aaa488b840983f87bd79b1054190e660de"
>
> -------------------------------------------------------------------------------
> NGINX Ingress controller
>   Release:       v1.1.1
>   Build:         a17181e43ec85534a6fea968d95d019c5a4bc8cf
>   Repository:    https://github.com/kubernetes/ingress-nginx
>   nginx version: nginx/1.19.9
> 
> -------------------------------------------------------------------------------
> 
> W0518 12:35:02.581996      10 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
> I0518 12:35:02.582086      10 main.go:223] "Creating API client" host="https://10.96.0.1:443"/
> I0518 12:35:02.585925      10 main.go:267] "Running in Kubernetes cluster" major="1" minor="26" git="v1.26.3" state="clean" commit="9e644106593f3f4aa98f8a84b23db5fa378900bd" platform="linux/amd64"
> I0518 12:35:03.009507      10 main.go:104] "SSL fake certificate created" file="/etc/ingress-controller/ssl/default-fake-certificate.pem"
> I0518 12:35:03.033020      10 nginx.go:255] "Starting NGINX Ingress controller"
> I0518 12:35:03.038172      10 event.go:282] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"default", Name:"ingress-nginx-controller", UID:"f4935a46-f505-4573-85fb-b0d8ccdb345a", APIVersion:"v1", ResourceVersion:"469", FieldPath:""}): type: 'Normal' reason: 'CREATE' ConfigMap default/ingress-nginx-controller
> failed to create fsnotify watcher: too many open files
> **I0518 12:35:03.009507      10 main.go:104] "SSL fake certificate created" file="/etc/ingress-controller/ssl/default-fake-certificate.pem"
> I0518 12:35:03.033020      10 nginx.go:255] "Starting NGINX Ingress controller"**
> I0518 12:35:03.038172      10 event.go:282] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"default", Name:"ingress-nginx-controller", UID:"f4935a46-f505-4573-85fb-b0d8ccdb345a", APIVersion:"v1", ResourceVersion:"469", FieldPath:""}): type: 'Normal' reason: 'CREATE' ConfigMap default/ingress-nginx-controller
> 

It worked! Thank you.

**Comment by rchen-virtru** [comment]
This is no longer an issue with the latest versions.
